In [1]:
!pip install pandas

Requirement already satisfied: pandas in ./tp2/lib/python3.12/site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in ./tp2/lib/python3.12/site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in ./tp2/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./tp2/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
!pip install wget

Requirement already satisfied: wget in ./tp2/lib/python3.12/site-packages (3.2)

In [3]:
from wget import download
from os import path, listdir

if not path.exists("ObesityDataSet_raw_and_data_sinthetic.txt"):
    download("https://ignaciorlando.github.io/datasets/data-science/ObesityDataSet_raw_and_data_sinthetic.txt")
else:
    print("El archivo ya existe")

if not path.exists("ObesityDataSet_raw_and_data_sinthetic.csv"):
    download("https://ignaciorlando.github.io/datasets/data-science/ObesityDataSet_raw_and_data_sinthetic.csv")
else:
    print("El archivo ya existe")

lista_archivos = listdir("./")
print(f"Los datos de la carpeta son: {lista_archivos}")

El archivo ya existe
El archivo ya existe
Los datos de la carpeta son: ['.gitignore', 'ObesityDataSet_raw_and_data_sinthetic.txt', 'tp2', 'catalogo_streaming_argentina_2024.xlsx', 'ObesityDataSet_raw_and_data_sinthetic.csv', 'netflix_titles.csv', 'tp2.ipynb', 'netflix_titles.txt', '.ipynb_checkpoints']

In [4]:
import pandas as pd

In [5]:
with open("ObesityDataSet_raw_and_data_sinthetic.txt", "r", encoding = "utf-8") as f:
    print(f.read())

Obesidad

La obesidad, que causa problemas físicos y mentales, es un problema de salud global con graves consecuencias. La prevalencia de la obesidad aumenta constantemente, por lo que se necesita nueva investigación que examine los factores que influyen en la obesidad y cómo predecir la aparición de la condición según estos factores.

Los datos fueron recolectados como parte de este trabajo científico: https://www.sciencedirect.com/science/article/pii/S2352340919306985#sec1

Información del Conjunto de Datos

Este conjunto de datos incluye información para la estimación de los niveles de obesidad en individuos de los países de México, Perú y Colombia, en función de sus hábitos alimenticios y condición física. Los datos contienen 17 atributos y 2111 registros, los registros están etiquetados con la variable de clase NObesidad (Nivel de Obesidad), que permite la clasificación de los datos utilizando los valores de Peso Insuficiente, Peso Normal, Sobrepeso Nivel I, Sobrepeso Nivel II, Obesidad Tipo I, Obesidad Tipo II y Obesidad Tipo III. El 77% de los datos se generó sintéticamente utilizando la herramienta Weka y el filtro SMOTE, el 23% de los datos se recolectaron directamente de los usuarios a través de una plataforma web.

Las columnas corresponden a:

Age: age

Height: height

Weight: weight

family_history_with_overweight: Has a family member suffered or suffers f from overweight? - yes or no

FAVC: Frequent consumption of high caloric food - yes or no

FCVC: Frequency of consumption of vegetables - Never, Sometimes, Always

NCP: Number of main meals - 1, 2, 3, 4

CAEC: Consumption of food between meals - No, Sometimes, Frequently, Always

SMOKE: Do you smoke - yes o no

CH2O: Consumption of water daily - Less than a litter, between 1 and 2 l, more than 2 l

SCC: Calories consumption monitoring - yes or no

FAF: Physical activity frequency - 0, 1 to 2, 2 to 4, 4 to 5

TUE: Time using technology devices - 0 to 2, 3 to 5, >5

CALC: Consumption of alcohol - no, sometimes, frequently, always

MTRANS: Transportation used - automobile, motorbike, bike, public_transportation, walking

NObeyesdad: Type of obesity - insufficient_weight, normal_weight, overweight-level_i, overweight-level_ii, obesity_type_i, obesity_type_ii, obesity_type_iii
BMI: Body mass index

In [6]:
#Leer archivo de datos

contenido_datos = pd.read_csv("ObesityDataSet_raw_and_data_sinthetic.csv")
contenido_datos

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad
0,21.000000,Female,1.620000,64.000000,no,no,2.0,3.0,no,no,2.000000,yes,0.000000,1.000000,Sometimes,Public_Transportation,Normal_Weight
1,21.000000,Female,1.520000,56.000000,Sometimes,no,3.0,3.0,yes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight
2,23.000000,Male,1.800000,77.000000,Frequently,no,2.0,3.0,no,no,2.000000,yes,2.000000,1.000000,Sometimes,Public_Transportation,Normal_Weight
3,27.000000,Male,1.800000,87.000000,Frequently,no,3.0,3.0,no,no,2.000000,no,2.000000,0.000000,Sometimes,Walking,Overweight_Level_I
4,22.000000,Male,1.780000,89.800000,Sometimes,no,2.0,1.0,no,no,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Overweight_Level_II
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,20.976842,Female,1.710730,131.408528,Sometimes,yes,3.0,3.0,no,no,1.728139,yes,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,21.982942,Female,1.748584,133.742943,Sometimes,yes,3.0,3.0,no,no,2.005130,yes,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,22.524036,Female,1.752206,133.689352,Sometimes,yes,3.0,3.0,no,no,2.054193,yes,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,24.361936,Female,1.739450,133.346641,Sometimes,yes,3.0,3.0,no,no,2.852339,yes,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,23.664709,Female,1.738836,133.472641,Sometimes,yes,3.0,3.0,no,no,2.863513,yes,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

In [7]:
#Imprimir los primeros 5 registros del archivo
contenido_datos.head()

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad
0,21.0,Female,1.62,64.0,no,no,2.0,3.0,no,no,2.0,yes,0.0,1.0,Sometimes,Public_Transportation,Normal_Weight
1,21.0,Female,1.52,56.0,Sometimes,no,3.0,3.0,yes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,23.0,Male,1.80,77.0,Frequently,no,2.0,3.0,no,no,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Normal_Weight
3,27.0,Male,1.80,87.0,Frequently,no,3.0,3.0,no,no,2.0,no,2.0,0.0,Sometimes,Walking,Overweight_Level_I
4,22.0,Male,1.78,89.8,Sometimes,no,2.0,1.0,no,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [8]:
#Imprimir la cabecera del archivo
contenido_datos.info()

<class 'pandas.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Age                             2111 non-null   float64
 1   Gender                          2111 non-null   str
 2   Height                          2111 non-null   float64
 3   Weight                          2111 non-null   float64
 4   CALC                            2111 non-null   str
 5   FAVC                            2111 non-null   str
 6   FCVC                            2111 non-null   float64
 7   NCP                             2111 non-null   float64
 8   SCC                             2111 non-null   str
 9   SMOKE                           2111 non-null   str
 10  CH2O                            2111 non-null   float64
 11  family_history_with_overweight  2111 non-null   str
 12  FAF                             2111 non-null   float64
 13  TUE                             2111 non-null   float64
 14  CAEC                            2111 non-null   str
 15  MTRANS                          2111 non-null   str
 16  NObeyesdad                      2111 non-null   str
dtypes: float64(8), str(9)
memory usage: 280.5 KB

In [9]:
#Imprimir resumen estadistico
contenido_datos.describe()

,Age,Height,Weight,FCVC,NCP,CH2O,FAF,TUE
count,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000
mean,24.312600,1.701677,86.586058,2.419043,2.685628,2.008011,1.010298,0.657866
std,6.345968,0.093305,26.191172,0.533927,0.778039,0.612953,0.850592,0.608927
min,14.000000,1.450000,39.000000,1.000000,1.000000,1.000000,0.000000,0.000000
25%,19.947192,1.630000,65.473343,2.000000,2.658738,1.584812,0.124505,0.000000
50%,22.777890,1.700499,83.000000,2.385502,3.000000,2.000000,1.000000,0.625350
75%,26.000000,1.768464,107.430682,3.000000,3.000000,2.477420,1.666678,1.000000
max,61.000000,1.980000,173.000000,3.000000,4.000000,3.000000,3.000000,2.000000

Age: Representa la edad del individuo - Cuanti - Discreta <br>
Height: Representa la altura - Cuanti - Continua <br>
Weight: Respresneta el peso - Cuanti - Continua <br>
family_history_with_overweight: Represente una antecendente familiar, si algun familiar sufre o sufrio obecidad - Cuali - Nominal - Binaria <br>
FAVC: Representa si el individuo consume frecuentemente comida con muchas calorias - Cuali - Nominal - Binaria<br>

# Ejercicio 2

In [10]:
from wget import download
from os import path, listdir

if not path.exists("netflix_titles.txt"):
    download("https://ignaciorlando.github.io/datasets/data-science/netflix_titles.txt")
else: 
    print("El archivo ya existe")

if not path.exists("netflix_titles.csv"):
    download("https://ignaciorlando.github.io/datasets/data-science/netflix_titles.csv")
else: 
    print("El archivo ya existe")

lista_achivos_netflix = listdir("./")
print(f"Contenido de la carpeta: {lista_achivos_netflix}")

El archivo ya existe
El archivo ya existe
Contenido de la carpeta: ['.gitignore', 'ObesityDataSet_raw_and_data_sinthetic.txt', 'tp2', 'catalogo_streaming_argentina_2024.xlsx', 'ObesityDataSet_raw_and_data_sinthetic.csv', 'netflix_titles.csv', 'tp2.ipynb', 'netflix_titles.txt', '.ipynb_checkpoints']

In [11]:
with open("netflix_titles.txt", "r", encoding="utf-8") as f:
    print(f.read())

Películas y Series de TV de Netflix

Acerca del Conjunto de Datos

Netflix es una fuerza líder en el ámbito de los medios y la transmisión de video. Con una asombrosa variedad de más de 8,000 películas y programas de televisión accesibles en su plataforma, a mediados de 2021, su cantidad de suscriptores globales superaba los 200 millones. Este conjunto de datos tabulado cataloga exhaustivamente todas las ofertas en Netflix, incluidos detalles vitales como elenco, directores, calificaciones, año de lanzamiento, duración y más.

Descripción General del Conjunto de Datos:

El conjunto de datos de Títulos de Netflix es una compilación completa de películas y programas de televisión disponibles en Netflix, que cubre diversos aspectos como el tipo de título, director, elenco, país de producción, año de lanzamiento, calificación, duración, géneros (listados) y una breve descripción. Este conjunto de datos es fundamental para analizar tendencias en el contenido de Netflix, comprender la popularidad de los géneros y examinar la distribución del contenido en diferentes regiones y períodos de tiempo.

In [12]:
import pandas as pd
leer_datos_netflix = pd.read_csv("netflix_titles.csv", encoding="latin-1")
#Al intentar cargar el archivo utilizando UTF-8 se produjo un UnicodeDecodeError, 
# indicando que el archivo contiene caracteres que no pueden ser interpretados utilizando dicha codificación. 
# Se utilizó la codificación latin-1, con la cual el archivo pudo ser cargado correctamente.

In [13]:
leer_datos_netflix.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
leer_datos_netflix.columns.tolist()

['show_id',
 'type',
 'title',
 'director',
 'cast',
 'country',
 'date_added',
 'release_year',
 'rating',
 'duration',
 'listed_in',
 'description',
 'Unnamed: 12',
 'Unnamed: 13',
 'Unnamed: 14',
 'Unnamed: 15',
 'Unnamed: 16',
 'Unnamed: 17',
 'Unnamed: 18',
 'Unnamed: 19',
 'Unnamed: 20',
 'Unnamed: 21',
 'Unnamed: 22',
 'Unnamed: 23',
 'Unnamed: 24',
 'Unnamed: 25']

In [15]:
leer_datos_netflix.shape

(8809, 26)

In [16]:
leer_datos_netflix.info()

<class 'pandas.DataFrame'>
RangeIndex: 8809 entries, 0 to 8808
Data columns (total 26 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8809 non-null   str
 1   type          8809 non-null   str
 2   title         8809 non-null   str
 3   director      6175 non-null   str
 4   cast          7984 non-null   str
 5   country       7978 non-null   str
 6   date_added    8799 non-null   str
 7   release_year  8809 non-null   int64
 8   rating        8805 non-null   str
 9   duration      8806 non-null   str
 10  listed_in     8809 non-null   str
 11  description   8809 non-null   str
 12  Unnamed: 12   0 non-null      float64
 13  Unnamed: 13   0 non-null      float64
 14  Unnamed: 14   0 non-null      float64
 15  Unnamed: 15   0 non-null      float64
 16  Unnamed: 16   0 non-null      float64
 17  Unnamed: 17   0 non-null      float64
 18  Unnamed: 18   0 non-null      float64
 19  Unnamed: 19   0 non-null      float64
 20  Unnamed: 20   0 non-null      float64
 21  Unnamed: 21   0 non-null      float64
 22  Unnamed: 22   0 non-null      float64
 23  Unnamed: 23   0 non-null      float64
 24  Unnamed: 24   0 non-null      float64
 25  Unnamed: 25   0 non-null      float64
dtypes: float64(14), int64(1), str(11)
memory usage: 1.7 MB

In [17]:
# Hay columnas que no representan nada, verifico si todas tienen NaN
leer_datos_netflix.iloc[:, 12:].isna().all().all()
leer_datos_netflix.iloc[:, 12:].notna().sum()

Unnamed: 12    0
Unnamed: 13    0
Unnamed: 14    0
Unnamed: 15    0
Unnamed: 16    0
Unnamed: 17    0
Unnamed: 18    0
Unnamed: 19    0
Unnamed: 20    0
Unnamed: 21    0
Unnamed: 22    0
Unnamed: 23    0
Unnamed: 24    0
Unnamed: 25    0
dtype: int64

In [18]:
# Ejecute head -n 3 netflix_titles.csv y head -n 1 netflix_titles.csv | awk -F',' '{print NF}'
# para comprobar como esta siendo interpretaado el archivo y se puede ver que hay varias comas juntas sin info
# Elimino esas columnas vacias
leer_datos_netflix = leer_datos_netflix.loc[:, ~leer_datos_netflix.columns.str.startswith("Unnamed")]
leer_datos_netflix.shape

(8809, 12)

In [19]:
leer_datos_netflix.info()

<class 'pandas.DataFrame'>
RangeIndex: 8809 entries, 0 to 8808
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8809 non-null   str
 1   type          8809 non-null   str
 2   title         8809 non-null   str
 3   director      6175 non-null   str
 4   cast          7984 non-null   str
 5   country       7978 non-null   str
 6   date_added    8799 non-null   str
 7   release_year  8809 non-null   int64
 8   rating        8805 non-null   str
 9   duration      8806 non-null   str
 10  listed_in     8809 non-null   str
 11  description   8809 non-null   str
dtypes: int64(1), str(11)
memory usage: 826.0 KB

In [20]:
leer_datos_netflix.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [21]:
leer_datos_netflix.describe()

       release_year
count   8809.000000
mean    2014.181292
std        8.818932
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2024.000000

Solo aparece el analisis de la columna release_year porque es de tipo numerico (cuanti - discreta), las demas columnas son objetos (texto/categoricas) tipo cualitativas

In [22]:
leer_datos_netflix.describe(include="object")

/tmp/ipykernel_6295/3271686078.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  leer_datos_netflix.describe(include="object")

,show_id,type,title,director,cast,country,date_added,rating,duration,listed_in,description
count,8809,8809,8809,6175,7984,7978,8799,8805,8806,8809,8809
unique,8809,2,8806,4529,7694,748,1768,18,220,516,8777
top,s1,Movie,15-Aug,Rajiv Chilaka,David Attenborough,United States,"January 1, 2020",TV-MA,1 Season,"Dramas, International Movies","Paranormal activity at a lush, abandoned prope..."
freq,1,6132,2,19,19,2819,109,3208,1794,362,4

In [23]:
leer_datos_netflix.release_year

0       2020
1       2021
2       2021
3       2021
4       2021
        ...
8804    2009
8805    2006
8806    2015
8807    2024
8808    2014
Name: release_year, Length: 8809, dtype: int64

__show_id__: Respresenta un identificador único para diferneciar una peli de las demas. Cuanli - Ordinal <br>
__type__: Representa el formato o categoría del contenido. Cuali - Nominal <br>
__title__: Representa el nombre de la pelicula. Cuali - Nominal <br>
__director__: Representa el nombre del director. Cuali - Nominal <br>
__cast__: Representa las personas que participaron en la pelicula. Cuali - Nominal <br>
__country__: Pais de origen de la peli. Cuali - Nominal <br>
__date-added__: Fecha que se agrego a la plataforma. Cuali - Nominal <br>
__release_year__: Fecha de estreno. Cuanti - Discreta. <br>
__rating__: Audiencia. Cuali - Nominal <br>
__duration__: Duracion de la peli. Cuali - Nominal <br>
__listed_in__: Categorias de la peli. Cuali - Nominal <br>
__description__: Texto que dice de que trata la peli. Cuali - Nominal <br>

In [24]:
leer_datos_netflix.director

0       Kirsten Johnson
1                   NaN
2       Julien Leclercq
3                   NaN
4                   NaN
             ...
8804    Ruben Fleischer
8805       Peter Hewitt
8806        Mozez Singh
8807       Yeon Sang-ho
8808       Susanne Bier
Name: director, Length: 8809, dtype: str

In [25]:
# Cuantos directores distintos hay
#Primero separo las peliculas que tienen mas de un director
directores = leer_datos_netflix["director"].str.split(",").explode().str.strip()
cant_directores_distintos = directores.nunique()
print(cant_directores_distintos)

4994

In [26]:
# Quien es el director con mas peliculas
# Cuento cuantas veces aparece el mismo director
director_cant_peliculas = directores.value_counts()
# Busco el maximo (el que mas salio)
director_mas_peliculas = director_cant_peliculas.idxmax()
cant_peliculas_del_director = director_cant_peliculas.max()
print(f"El director con mas peliculas es {director_mas_peliculas} con {cant_peliculas_del_director} peliculas")

El director con mas peliculas es Rajiv Chilaka con 22 peliculas

In [27]:
# Cuantas series series hay y cuantos programas de TV
cant_tv_shows_y_movies = leer_datos_netflix["type"].value_counts()
print(cant_tv_shows_y_movies)

type
Movie      6132
TV Show    2677
Name: count, dtype: int64

In [28]:
# Pelicula y serie mas vieja del catalogo
peliculas = leer_datos_netflix[leer_datos_netflix["type"] == "Movie"]
pelicula_mas_vieja = peliculas.loc[peliculas["release_year"].idxmin()]
series = leer_datos_netflix[leer_datos_netflix["type"] == "TV Show"]
serie_mas_vieja = series.loc[series["release_year"].idxmin()]
print(peliculas)
print(pelicula_mas_vieja)
print()
print(serie_mas_vieja)

     show_id   type                             title  \
0         s1  Movie              Dick Johnson Is Dead
6         s7  Movie  My Little Pony: A New Generation
7         s8  Movie                           Sankofa
9        s10  Movie                      The Starling
12       s13  Movie                      Je Suis Karl
...      ...    ...                               ...
8802   s8803  Movie                            Zodiac
8804   s8805  Movie                        Zombieland
8805   s8806  Movie                              Zoom
8806   s8807  Movie                            Zubaan
8808   s8809  Movie                            Serena

                            director  \
0                    Kirsten Johnson
6     Robert Cullen, JosÃ© Luis Ucha
7                       Haile Gerima
9                     Theodore Melfi
12               Christian Schwochow
...                              ...
8802                   David Fincher
8804                 Ruben Fleischer
8805                    Peter Hewitt
8806                     Mozez Singh
8808                    Susanne Bier

                                                   cast  \
0                                                   NaN
6     Vanessa Hudgens, Kimiko Glenn, James Marsden, ...
7     Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...
9     Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...
12    Luna Wedler, Jannis NiewÃ¶hner, Milan Peschel,...
...                                                 ...
8802  Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...
8804  Jesse Eisenberg, Woody Harrelson, Emma Stone, ...
8805  Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...
8806  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...
8808  Bradley Cooper, Jennifer Lawrence, Toby Jones,...

                                                country          date_added  \
0                                         United States  September 25, 2021
6                                                   NaN  September 24, 2021
7     United States, Ghana, Burkina Faso, United Kin...  September 24, 2021
9                                         United States  September 24, 2021
12                              Germany, Czech Republic  September 23, 2021
...                                                 ...                 ...
8802                                      United States   November 20, 2019
8804                                      United States    November 1, 2019
8805                                      United States    January 11, 2020
8806                                              India       March 2, 2019
8808                                      United States       April 5, 2024

      release_year rating duration  \
0             2020  PG-13   90 min
6             2021     PG   91 min
7             1993  TV-MA  125 min
9             2021  PG-13  104 min
12            2021  TV-MA  127 min
...            ...    ...      ...
8802          2007      R  158 min
8804          2009      R   88 min
8805          2006     PG   88 min
8806          2015  TV-14  111 min
8808          2014      A  110 min

                                             listed_in  \
0                                        Documentaries
6                             Children & Family Movies
7     Dramas, Independent Movies, International Movies
9                                     Comedies, Dramas
12                        Dramas, International Movies
...                                                ...
8802                    Cult Movies, Dramas, Thrillers
8804                           Comedies, Horror Movies
8805                Children & Family Movies, Comedies
8806    Dramas, International Movies, Music & Musicals
8808                          Drama, Romance, Thriller

                                            description
0     As her father nears the end of his life, filmm...
6     Equestria's divided. But a bright-eyed hero be...
7     On a photo shoot in Ghana, an American model s...
9     A woman adjusting to life after a loss contend...
12    After most of her family is murdered in a terr...
...                                                 ...
8802  A political cartoonist, a crime reporter and a...
8804  Looking to survive in a world taken over by zo...
8805  Dragged from civilian life, a former superhero...
8806  A scrappy but poor boy worms his way into a ty...
8808  In the 1920s, a newly married couple attempt t...

[6132 rows x 12 columns]
show_id                                                     s7791
type                                                        Movie
title                                              Prelude to War
director                                              Frank Capra
cast                                                          NaN
country                                             United States
date_added                                         March 31, 2017
release_year                                                 1942
rating                                                      TV-14
duration                                                   52 min
listed_in                           Classic Movies, Documentaries
description     Frank Capra's documentary chronicles the rise ...
Name: 7790, dtype: object

show_id                                                     s4251
type                                                      TV Show
title                           Pioneers: First Women Filmmakers*
director                                                      NaN
cast                                                          NaN
country                                                       NaN
date_added                                      December 30, 2018
release_year                                                 1925
rating                                                      TV-14
duration                                                 1 Season
listed_in                                                TV Shows
description     This collection restores films from women who ...
Name: 4250, dtype: object

In [29]:
# Dado un país, determinar cuántas películas de ese país hay en la base de datos.
pais = input("Ingrese el nombre de un pais: ")
peliculas_del_pais = leer_datos_netflix[(leer_datos_netflix["type"] == "Movie") & (leer_datos_netflix["country"].str.contains(pais, na=False))]

print(f"Hay {len(peliculas_del_pais)} peliculas de {pais}")

Hay 114 peliculas de China

# Ejercicio 3

In [30]:
if not path.exists("catalogo_streaming_argentina_2024.xlsx"):
    download("https://ignaciorlando.github.io/datasets/data-science/catalogo_streaming_argentina_2024.xlsx")
else:
    print("El archivo ya existe")

listar_streaming_arg = listdir("./")
print(f"El contenido del archivo es: {listar_streaming_arg}")

El archivo ya existe
El contenido del archivo es: ['.gitignore', 'ObesityDataSet_raw_and_data_sinthetic.txt', 'tp2', 'catalogo_streaming_argentina_2024.xlsx', 'ObesityDataSet_raw_and_data_sinthetic.csv', 'netflix_titles.csv', 'tp2.ipynb', 'netflix_titles.txt', '.ipynb_checkpoints']

In [31]:
leer_streaming_arg = pd.read_excel("catalogo_streaming_argentina_2024.xlsx")
leer_streaming_arg

,title,platform,type,imdbVotes,imdbScore,tmdbPopularity,tmdbScore,runtime,genres,director,year_range,url
0,Cadena perpetua,Max,MOVIE,2906253.0,9.3,159.594,8.705,142,"Drama, Crimen",Frank Darabont,1900_2002,https://play.max.com/movie/9b4dacba-2f80-4272-...
1,El caballero oscuro,Max,MOVIE,2893241.0,9.0,111.674,8.516,152,"Misterio & Suspense, Drama, Acción & Aventura,...",Christopher Nolan,2003_2010,https://play.max.com/movie/52217243-a137-45d6-...
2,Origen,Max,MOVIE,2570263.0,8.8,139.644,8.369,148,"Ciencia ficción, Acción & Aventura, Misterio &...",Christopher Nolan,2003_2010,https://play.max.com/movie/14552c93-d318-4563-...
3,El club de la lucha,Disney Plus,MOVIE,2345071.0,8.8,108.297,8.400,139,Drama,David Fincher,1998_2004,https://disneyplus.bn5x.net/c/1206980/705874/9...
4,El club de la lucha,Netflix,MOVIE,2345071.0,8.8,108.297,8.400,139,Drama,David Fincher,1995_2005,http://www.netflix.com/title/26004747
...,...,...,...,...,...,...,...,...,...,...,...,...
19812,Три кота,Netflix,SHOW,NaN,NaN,13.684,5.400,5,Ciencia ficción,NaN,2013_2017,http://www.netflix.com/title/81208524
19813,أم الدراهم,Amazon Prime Video,SHOW,NaN,NaN,0.858,NaN,29,Comedia,NaN,2021,https://app.primevideo.com/detail?gti=amzn1.dv...
19814,ورق مسموم,Amazon Prime Video,SHOW,NaN,NaN,0.600,NaN,48,NaN,NaN,2022,https://app.primevideo.com/detail?gti=amzn1.dv...
19815,ガクドリ,Amazon Prime Video,MOVIE,NaN,NaN,2.841,NaN,90,NaN,Kei Era,2011_2013,https://app.primevideo.com/detail?gti=amzn1.dv...
19816,新歌舞伎：赤胴鈴之助,Netflix,MOVIE,NaN,NaN,3.203,NaN,169,Fantasía,Kikunojo Onoe,2022,http://www.netflix.com/title/81517566

In [32]:
leer_streaming_arg.info()

<class 'pandas.DataFrame'>
RangeIndex: 19817 entries, 0 to 19816
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           19817 non-null  object
 1   platform        19817 non-null  str
 2   type            19817 non-null  str
 3   imdbVotes       17854 non-null  float64
 4   imdbScore       17927 non-null  float64
 5   tmdbPopularity  19538 non-null  float64
 6   tmdbScore       18954 non-null  float64
 7   runtime         19817 non-null  int64
 8   genres          19665 non-null  str
 9   director        14626 non-null  str
 10  year_range      19817 non-null  object
 11  url             19817 non-null  str
dtypes: float64(4), int64(1), object(2), str(5)
memory usage: 1.8+ MB

In [33]:
leer_streaming_arg.head()

,title,platform,type,imdbVotes,imdbScore,tmdbPopularity,tmdbScore,runtime,genres,director,year_range,url
0,Cadena perpetua,Max,MOVIE,2906253.0,9.3,159.594,8.705,142,"Drama, Crimen",Frank Darabont,1900_2002,https://play.max.com/movie/9b4dacba-2f80-4272-...
1,El caballero oscuro,Max,MOVIE,2893241.0,9.0,111.674,8.516,152,"Misterio & Suspense, Drama, Acción & Aventura,...",Christopher Nolan,2003_2010,https://play.max.com/movie/52217243-a137-45d6-...
2,Origen,Max,MOVIE,2570263.0,8.8,139.644,8.369,148,"Ciencia ficción, Acción & Aventura, Misterio &...",Christopher Nolan,2003_2010,https://play.max.com/movie/14552c93-d318-4563-...
3,El club de la lucha,Disney Plus,MOVIE,2345071.0,8.8,108.297,8.400,139,Drama,David Fincher,1998_2004,https://disneyplus.bn5x.net/c/1206980/705874/9...
4,El club de la lucha,Netflix,MOVIE,2345071.0,8.8,108.297,8.400,139,Drama,David Fincher,1995_2005,http://www.netflix.com/title/26004747

In [34]:
leer_streaming_arg.describe()

          imdbVotes     imdbScore  tmdbPopularity     tmdbScore       runtime
count  1.785400e+04  17927.000000    19538.000000  18954.000000  19817.000000
mean   4.838858e+04      6.399520       41.195589      6.461363     80.542867
std    1.488473e+05      1.200258      131.031366      1.254487     37.092943
min    5.000000e+00      1.100000        0.001000      0.500000      0.000000
25%    4.620000e+02      5.700000        5.433250      5.889500     48.000000
50%    2.849500e+03      6.500000       14.428500      6.600000     89.000000
75%    2.196975e+04      7.300000       33.312500      7.273750    105.000000
max    2.906253e+06      9.700000     4173.518000     10.000000    263.000000

In [36]:
leer_streaming_arg.describe(include = "object")

/tmp/ipykernel_6295/3570371411.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  leer_streaming_arg.describe(include = "object")

,title,platform,type,genres,director,year_range,url
count,19817,19817,19817,19665,14626,19817,19817
unique,18008,6,2,4189,8812,27,19062
top,Perdida,Netflix,MOVIE,Documental,Steven Spielberg,2022,http://www.netflix.com/title/81665878
freq,5,7109,14060,1277,27,1697,2

__title__: Titulo de la pelicula. Cuanli - Nominal <br>
__platform__: Plataforma donde se encuentra la pelicula. Cuali - Nominal <br>
__type__: Deescribe si es una pelicula o serie. Cuali - Nominal <br>
__imdbVotes__: Cantidad de votos en IMDB. Cuanti - Discreta <br>
__imdbScore__: Valoracion de la pelicula en IMDB. Cuanti - Continua <br>
__tmdbPopularity__: Pupolaridad en TMDB. Cuanti - Continua <br>
__tmdbScore__: Valoracion en TMDB. Cuanti - Continua <br>
__runtime__: Duracion de la pelicula en minutos. Cuanti - Discreta <br>
__genres__: Generos de la pelicula. Cuali - Nominal <br>
__director__: Director de la pelicula. Cuali - Nominal <br>
__year_range__: Rango de edad para verla. Cuali - Nominal <br>
__url__: Direccion web para ver la pelicula. Cuali - Nominal <br>

In [41]:
# Cuanto contenido tiene cada plataforma
contenido_por_plataforma = leer_streaming_arg["platform"].value_counts()
print(contenido_por_plataforma)

# Y cual es la plataforma con mas contenido
plataforma_mas_contenido = contenido_por_plataforma.idxmax()
cant_plataforma_mas_contenido = contenido_por_plataforma.max()
print(f"La plataforma con mas contenido es {plataforma_mas_contenido} con {cant_plataforma_mas_contenido}")

platform
Netflix               7109
Amazon Prime Video    6436
Disney Plus           2980
Max                   2585
Paramount Plus         475
Apple TV Plus          232
Name: count, dtype: int64
La plataforma con mas contenido es Netflix con 7109

In [ ]:
# Cuantas peliculas y series hay
cant_peliculas_series = leer_streaming_arg["type"].value_counts()
print(cant_peliculas_series)

type
MOVIE    14060
SHOW      5757
Name: count, dtype: int64

In [52]:
plataforma = input("Ingrese una plataforma: ")

if plataforma in contenido_por_plataforma.index:
    contenido_plataforma = contenido_por_plataforma[plataforma]
    print(f"{plataforma} tiene {contenido_plataforma} contenidos.")
else:
    print(f"No se encontró la plataforma {plataforma}.")

Netflix tiene 7109 contenidos.

In [53]:
# Plataforma con mayor catidad de peliculas
peliculas_streaming = leer_streaming_arg[leer_streaming_arg["type"] == "MOVIE"]
peliculas_por_plataforma = peliculas_streaming.groupby("platform").size()
platform_max = peliculas_por_plataforma.idxmax()
cantidad_max = peliculas_por_plataforma.max()
print(f"La plataforma con mas peliculas es {platform_max} con {cantidad_max} peliculas")

La plataforma con mas peliculas es Amazon Prime Video con 5322 peliculas

In [55]:
# Plataforma con mayor cantidad de series
series_streaming = leer_streaming_arg[leer_streaming_arg["type"] == "SHOW"]
series_por_plataforma = series_streaming.groupby("platform").size()
platform_max_series = series_por_plataforma.idxmax()
cantidad_max_series = series_por_plataforma.max()
print(f"La plataforma con mas peliculas es {platform_max_series} con {cantidad_max_series} series")

La plataforma con mas peliculas es Netflix con 2770 series

In [58]:
# Plataforma que tiene, en promedio, contenidos más popular
promedio_por_plataforma = leer_streaming_arg.groupby("platform")["tmdbPopularity"].mean()
print(promedio_por_plataforma)

platform
Amazon Prime Video     27.724315
Apple TV Plus          61.226336
Disney Plus            56.365132
Max                    54.397339
Netflix                36.507705
Paramount Plus        113.886256
Name: tmdbPopularity, dtype: float64